airfieldsData = {
    blueAirfields = {
        "Melez",
        "Hatzerim",
        "Nevatim",
        "Ramon Airbase",
        "Ovda",
        "Kedem",
        "Hatzor",
        "Palmachim",
        "Sde Dov",
        "Tel Nof",
        "Ben-Gurion",
        "St Catherine",
        "Abu Rudeis",
        "Baluza",
        "Bir Hasanah",
        "El Arish",
        "El Gora",
        "Hurghada International Airport",
        "Ramon International Airport",
        "Sharm El Sheikh International Airport",
        "Al Bahr al Ahmar",
    },
    redAirfields = {
        "Difarsuwar Airfield",
        "Abu Suwayr",
        "As Salihiyah",
        "Al Ismailiyah",
        "Fayed",
        "Kibrit Air Base",
        "Wadi al Jandali",
        "Al Mansurah",
        "AzZaqaziq",
        "Bilbeis Air Base",
        "Cairo International Airport",
        "Cairo West",
        "Inshas Airbase",
        "Al Khatatbah",
        "Al Rahmaniyah Air Base",
        "Beni Suef",
        "Birma Air Base",
        "Borg El Arab International Airport",
        "El Minya",
        "Gebel El Basur Air Base",
        "Jiyanklis Air Base",
        "Kom Awshim",
        "Wadi Abu Rish",
        "Quwaysina",
    }
}
