blueAirfields = {
    "Tha'lah",
    "Damascus",
    "Marj as Sultan South",
    "Al-Dumayr",
    "Eyn Shemer",
    "H4",
    "Haifa",
    "Khalkhalah",
    "King Hussein Air College",
    "Kiryat Shmona",
    "Marj as Sultan North",
    "Marj Ruhayyil",
    "Megiddo",
    "Mezzeh",
    "Qabr as Sitt",
    "Ramat David",
    "Rayak",
    "Rosh Pina",
    "Sayqal",
    "Naqoura",
    "H3",
    "H3 Northwest",
    "H3 Southwest",
    "Ruwayshid",
    "At Tanf",
    "Prince Hassan",
    "King Abdullah II",
    "Herzliya",
    "Marka",
    "Muwaffaq Salti",
    "Tel Nof",
    "Ben Gurion",
    "Hatzor",
    "Palmachim",
}
redAirfields = {
    "Abu al-Duhur",
    "Adana Sakirpasa",
    "Al Qusayr",
    "An Nasiriyah",
    "Beirut-Rafic Hariri",
    "Gaziantep",
    "Hama",
    "Hatay",
    "Incirlik",
    "Jirah",
    "Bassel Al-Assad",
    "Minakh",
    "Aleppo",
    "Palmyra",
    "Kuweires",
    "Rene Mouawad",
    "Shayrat",
    "Tabqa",
    "Taftanaz",
    "Tiyas",
    "Wujah Al Hajar",
    "Gazipasa",
    "Deir ez-Zor",
    "Nicosia",
    "Akrotiri",
    "Kingsfield",
    "Paphos",
    "Larnaca",
    "Lakatamia",
    "Ercan",
    "Gecitkale",
    "Pinarbashi",
    "Sanliurfa",
    "Kharab Ishk",
    "Tal Siman",
}
