blueAirfields = {
    "Tha'lah",
    "Damascus",
    "Al-Dumayr",
	"An Nasiriyah",
    "Eyn Shemer",
    "H4",
    "Haifa",
    "Khalkhalah",
    "King Hussein Air College",
    "Kiryat Shmona",
    "Mezzeh",
    "Qabr as Sitt",
    "Ramat David",
    "Rayak",
    "Rosh Pina",
    "Sayqal",
    "Naqoura",
    "H3",
    "Ruwayshid",
    "At Tanf",
    "Prince Hassan",
    "King Abdullah II",
    "Herzliya",
    "Muwaffaq Salti",
    "Hatzor",
}
redAirfields = {
    "Abu al-Duhur",
    "Al Qusayr",
    "Beirut-Rafic Hariri",
    "Gaziantep",
    "Hama",
    "Hatay",
    "Incirlik",
    "Jirah",
    "Bassel Al-Assad",
    "Aleppo",
    "Palmyra",
    "Rene Mouawad",
    "Shayrat",
    "Tabqa",
    "Taftanaz",
    "Tiyas",
    "Wujah Al Hajar",
    "Deir ez-Zor",
    "Nicosia",
    "Akrotiri",
    "Paphos",
    "Larnaca",
    "Gecitkale",
    "Pinarbashi",
    "Kharab Ishk",
}
