AllAircraft = {
    "A-10A",
    "A-10C",
    "A-10C_2",
    "A-20G",
    "A-4E-C",
    "A-50",
    "AH-1W",
    "AH-64A",
    "AH-64D",
    "AH-64D_BLK_II",
    "AJS37",
    "An-26B",
    "An-30M",
    "AV8BNA",
    "B-17G",
    "B-1B",
    "B-52H",
    "Bf-109K-4",
    "C-101CC",
    "C-101EB",
    "C-130",
    "C-17A",
    "C-47",
    "CH-47D",
    "CH-47Fbl1",
    "CH-53E",
    "Christen Eagle II",
    "E-2C",
    "E-3A",
    "F-117A",
    "F-14A",
    "F-14A-135-GR",
    "F-14B",
    "F-15C",
    "F-15E",
    "F-15ESE",
    "F-16A",
    "F-16A MLU",
    "F-16C bl.50",
    "F-16C bl.52d",
    "F-16C_50",
    "F-4E",
    "F-4E-45MC",
    "F-5E",
    "F-5E-3",
    "F-5E-3_FC",
    "F-86F Sabre",
    "F-86F_FC",
    "FA-18C_hornet",
    "Falcon_Gyrocopter",
    "FW-190A8",
    "FW-190D9",
    "H-6J",
    "Hawk",
    "Hercules",
    "IL-76MD",
    "IL-78M",
    "I-16",
    "J-11A",
    "JF-17",
    "Ju-88A4",
    "Ka-27",
    "Ka-50",
    "Ka-50_3",
    "KC-135",
    "KC130",
    "KC130J",
    "KC135MPRS",
    "KJ-2000",
    "L-39C",
    "L-39ZA",
    "MB-339A",
    "MB-339APAN",
    "Mi-24P",
    "Mi-24V",
    "Mi-26",
    "Mi-28N",
    "Mi-8MT",
    "MiG-15bis",
    "MiG-15bis_FC",
    "MiG-19P",
    "MiG-21Bis",
    "MiG-23MLD",
    "MiG-25PD",
    "MiG-25RBT",
    "MiG-27K",
    "MiG-29A",
    "MiG-29G",
    "MiG-29S",
    "MiG-31",
    "Mirage 2000-5",
    "Mirage-F1AD",
    "Mirage-F1AZ",
    "Mirage-F1B",
    "Mirage-F1BD",
    "Mirage-F1BE",
    "Mirage-F1BQ",
    "Mirage-F1C",
    "Mirage-F1C-200",
    "Mirage-F1CE",
    "Mirage-F1CH",
    "Mirage-F1CK",
    "Mirage-F1CJ",
    "Mirage-F1CK",
    "Mirage-F1CR",
    "Mirage-F1CT",
    "Mirage-F1CZ",
    "Mirage-F1DDA",
    "Mirage-F1EDA",
    "Mirage-F1ED",
    "Mirage-F1EE",
    "Mirage-F1EH",
    "Mirage-F1EQ",
    "Mirage-F1JA",
    "Mirage-F1M-CE",
    "Mirage-F1M-EE",
    "Mirage-F1",
    "MosquitoFBMkVI",
    "MQ-9 Reaper",
    "OH-58D",
    "OH58D",
    "P-47D-30",
    "P-47D-30bl1",
    "P-47D-40",
    "P-51D",
    "P-51D-30-NA",
    "RQ-1A Predator",
    "S-3B",
    "S-3B Tanker",
    "SA342L",
    "SA342M",
    "SA342Minigun",
    "SA342Mistral",
    "SH-3W",
    "SH-60B",
    "SpitfireLFMkIX",
    "SpitfireLFMkIXCW",
    "Su-17M4",
    "Su-24M",
    "Su-24MR",
    "Su-25",
    "Su-25T",
    "Su-25TM",
    "Su-27",
    "Su-30",
    "Su-33",
    "Su-34",
    "TF-51D",
    "Tornado GR4",
    "Tornado IDS",
    "Tu-142",
    "Tu-160",
    "Tu-22M3",
    "Tu-95MS",
    "UH-60A",
    "UH-1H",
    "WingLoong-I",
    "Yak-40",
    "Yak-52"
}

BlueAircraftCW78 = {
    "A-10A",
    "A-4E-C",
    "AH-1W",
    "B-52H"
    "C-101CC"
    "C-101EB"
    "C-130"
    "C-47",
    "CH-47D",
    "CH-47Fbl1",
    "CH-53E",
    "F-14A",
    "F-14A-135-GR",
    "F-14B",
    "F-4E",
    "F-4E-45MC",
    "F-5E",
    "F-5E-3",
    "F-5E-3_FC",
    "F-86F Sabre",
    "F-86F_FC",
    "Hercules",
    "Mirage-F1B",
    "Mirage-F1BD",
    "Mirage-F1BE",
    "Mirage-F1BQ",
    "Mirage-F1C",
    "Mirage-F1C-200",
    "Mirage-F1CE",
    "Mirage-F1CH",
    "Mirage-F1CK",
    "Mirage-F1CJ",
    "Mirage-F1CK",
    "Mirage-F1CR",
    "Mirage-F1CT",
    "Mirage-F1CZ",
    "Mirage-F1DDA",
    "Mirage-F1EDA",
    "Mirage-F1ED",
    "Mirage-F1EE",
    "Mirage-F1EH",
    "Mirage-F1EQ",
    "Mirage-F1JA",
    "Mirage-F1M-CE",
    "Mirage-F1M-EE",
    "Mirage-F1",
    "UH-1H",
    "Tornado GR4",
    "Tornado IDS",
}

RedAircraftCW78 = {
    "An-26B",
    "An-30M",
    "Ka-27",
    "Mi-24P",
    "Mi-24V",
    "Mi-26",
    "Mi-8MT",
    "MiG-15bis",
    "MiG-15bis_FC",
    "MiG-19P",
    "MiG-21Bis",
    "MiG-23MLD",
    "MiG-25PD",
    "MiG-25RBT",
    "MiG-27K",
    "Su-17M4",
    "Su-24M",
    "Su-24MR",
    "Su-25",
    "Su-25T",
    "Su-25TM",

}


Allweapons = {"weapons.nurs.SNEB_TYPE253_F1B" ,
"weapons.missiles.P_24T" ,
"weapons.bombs.BLU-3B_OLD" ,
"weapons.missiles.AGM_154" ,
"weapons.nurs.HYDRA_70_M151_M433" ,
"weapons.bombs.SAM Avenger M1097 Skid [7090lb]" ,
"weapons.bombs.British_GP_250LB_Bomb_Mk5" ,
"weapons.containers.{OV10_SMOKE}" ,
"weapons.bombs.BLU-4B_OLD" ,
"weapons.bombs.FAB-500M54" ,
"weapons.bombs.GBU_38" ,
"weapons.containers.F-15E_AXQ-14_DATALINK" ,
"weapons.bombs.BEER_BOMB" ,
"weapons.bombs.P-50T" ,
"weapons.nurs.C_8CM_GN" ,
"weapons.bombs.FAB-500SL" ,
"weapons.bombs.KAB_1500Kr" ,
"weapons.bombs.250-2" ,
"weapons.droptanks.Spitfire_tank_1" ,
"weapons.missiles.AGM_65G" ,
"weapons.missiles.AGM_65A" ,
"weapons.containers.Hercules_JATO" ,
"weapons.nurs.HYDRA_70_M259" ,
"weapons.missiles.AGM_84E" ,
"weapons.bombs.AN_M30A1" ,
"weapons.nurs.C_25" ,
"weapons.containers.AV8BNA_ALQ164" ,
"weapons.containers.lav-25" ,
"weapons.missiles.P_60" ,
"weapons.bombs.FAB_1500" ,
"weapons.droptanks.FuelTank_350L" ,
"weapons.bombs.AAA Vulcan M163 Skid [21577lb]" ,
"weapons.missiles.Kormoran" ,
"weapons.droptanks.HB_F14_EXT_DROPTANK_EMPTY" ,
"weapons.droptanks.FuelTank_150L" ,
"weapons.missiles.Rb 15F (for A.I.)" ,
"weapons.missiles.RB75T" ,
"weapons.missiles.Vikhr_M" ,
"weapons.nurs.FFAR M156 WP" ,
"weapons.nurs.British_HE_60LBSAPNo2_3INCHNo1" ,
"weapons.missiles.DWS39_MJ2" ,
"weapons.bombs.HEBOMBD" ,
"weapons.missiles.CATM_9M" ,
"weapons.bombs.Mk_81" ,
"weapons.droptanks.Drop_Tank_300_Liter" ,
"weapons.containers.HMMWV_M1025" ,
"weapons.bombs.SAM CHAPARRAL Air [21624lb]" ,
"weapons.missiles.AGM_154A" ,
"weapons.bombs.Mk_84AIR_TP" ,
"weapons.bombs.GBU_31_V_3B" ,
"weapons.nurs.C_8CM_WH" ,
"weapons.missiles.Matra Super 530D" ,
"weapons.nurs.ARF8M3TPSM" ,
"weapons.missiles.TGM_65H" ,
"weapons.nurs.M8rocket" ,
"weapons.bombs.GBU_27" ,
"weapons.missiles.AGR_20A" ,
"weapons.missiles.LS-6-250" ,
"weapons.droptanks.M2KC_RPL_522_EMPTY" ,
"weapons.droptanks.M2KC_02_RPL541" ,
"weapons.missiles.AGM_45" ,
"weapons.missiles.AGM_84A" ,
"weapons.bombs.APC BTR-80 Air [23936lb]" ,
"weapons.missiles.P_33E" ,
"weapons.missiles.Ataka_9M120" ,
"weapons.bombs.MK76" ,
"weapons.bombs.AB_250_2_SD_2" ,
"weapons.missiles.Rb 05A" ,
"weapons.bombs.ART GVOZDIKA [34720lb]" ,
"weapons.bombs.Generic Crate [20000lb]" ,
"weapons.bombs.FAB_100SV" ,
"weapons.bombs.BetAB_500" ,
"weapons.droptanks.M2KC_02_RPL541_EMPTY" ,
"weapons.droptanks.PTB600_MIG15" ,
"weapons.missiles.Rb 24J" ,
"weapons.nurs.C_8CM_BU" ,
"weapons.nurs.SNEB_TYPE259E_F1B" ,
"weapons.nurs.WGr21" ,
"weapons.bombs.SAMP250HD" ,
"weapons.containers.alq-184long" ,
"weapons.nurs.SNEB_TYPE259E_H1" ,
"weapons.bombs.British_SAP_250LB_Bomb_Mk5" ,
"weapons.bombs.Transport UAZ-469 Air [3747lb]" ,
"weapons.bombs.Mk_83CT" ,
"weapons.missiles.AIM-7P" ,
"weapons.missiles.AT_6" ,
"weapons.nurs.SNEB_TYPE254_H1_GREEN" ,
"weapons.nurs.SNEB_TYPE250_F1B" ,
"weapons.containers.U22A" ,
"weapons.bombs.British_GP_250LB_Bomb_Mk1" ,
"weapons.bombs.CBU_105" ,
"weapons.droptanks.FW-190_Fuel-Tank" ,
"weapons.missiles.X_58" ,
"weapons.missiles.BK90_MJ1_MJ2" ,
"weapons.missiles.TGM_65D" ,
"weapons.containers.BRD-4-250" ,
"weapons.missiles.P_73" ,
"weapons.bombs.AN_M66" ,
"weapons.bombs.APC LAV-25 Air [22520lb]" ,
"weapons.missiles.AIM-7MH" ,
"weapons.containers.MB339_TravelPod" ,
"weapons.bombs.GBU_12" ,
"weapons.bombs.SC_250_T3_J" ,
"weapons.missiles.KD-20" ,
"weapons.missiles.AGM_86C" ,
"weapons.missiles.X_35" ,
"weapons.bombs.MK106" ,
"weapons.bombs.BETAB-500S" ,
"weapons.nurs.C_5" ,
"weapons.nurs.S-24B" ,
"weapons.bombs.British_MC_500LB_Bomb_Mk2" ,
"weapons.containers.ANAWW_13" ,
"weapons.droptanks.droptank_108_gal" ,
"weapons.droptanks.DFT_300_GAL_A4E_LR" ,
"weapons.bombs.CBU_87" ,
"weapons.missiles.GAR-8" ,
"weapons.bombs.BELOUGA" ,
"weapons.containers.{EclairM_33}" ,
"weapons.bombs.ART 2S9 NONA Air [19140lb]" ,
"weapons.bombs.BR_250" ,
"weapons.bombs.IAB-500" ,
"weapons.containers.AN_ASQ_228" ,
"weapons.missiles.P_27P" ,
"weapons.bombs.SD_250_Stg" ,
"weapons.missiles.R_530F_IR" ,
"weapons.bombs.British_SAP_500LB_Bomb_Mk5" ,
"weapons.bombs.FAB-250M54" ,
"weapons.containers.{M2KC_AAF}" ,
"weapons.missiles.CM-802AKG_AI" ,
"weapons.bombs.CBU_103" ,
"weapons.containers.{US_M10_SMOKE_TANK_RED}" ,
"weapons.missiles.X_29T" ,
"weapons.bombs.HEMTT TFFT [34400lb]" ,
"weapons.missiles.C-701IR" ,
"weapons.containers.fullCargoSeats" ,
"weapons.bombs.GBU_15_V_31_B" ,
"weapons.bombs.APC M1043 HMMWV Armament Air [7023lb]" ,
"weapons.missiles.PL-5EII" ,
"weapons.bombs.SC_250_T1_L2" ,
"weapons.torpedoes.mk46torp_name" ,
"weapons.containers.F-15E_AAQ-33_XR_ATP-SE" ,
"weapons.missiles.AIM_7" ,
"weapons.missiles.AGM_122" ,
"weapons.bombs.HEBOMB" ,
"weapons.bombs.CBU_97" ,
"weapons.bombs.MK-81SE" ,
"weapons.nurs.Zuni_127" ,
"weapons.containers.{M2KC_AGF}" ,
"weapons.droptanks.Hercules_ExtFuelTank" ,
"weapons.containers.{SMOKE_WHITE}" ,
"weapons.droptanks.droptank_150_gal" ,
"weapons.nurs.HYDRA_70_WTU1B" ,
"weapons.missiles.GB-6-SFW" ,
"weapons.missiles.KD-63" ,
"weapons.bombs.GBU_28" ,
"weapons.nurs.C_8CM_YE" ,
"weapons.droptanks.HB_F14_EXT_DROPTANK" ,
"weapons.missiles.Super_530F" ,
"weapons.missiles.Ataka_9M220" ,
"weapons.bombs.BDU_33" ,
"weapons.bombs.British_GP_250LB_Bomb_Mk4" ,
"weapons.missiles.TOW" ,
"weapons.bombs.ATGM M1045 HMMWV TOW Air [7183lb]" ,
"weapons.missiles.X_25MR" ,
"weapons.droptanks.fueltank230" ,
"weapons.droptanks.PTB-490C-MIG21" ,
"weapons.bombs.M1025 HMMWV Air [6160lb]" ,
"weapons.nurs.SNEB_TYPE254_F1B_GREEN" ,
"weapons.missiles.R_550" ,
"weapons.bombs.KAB_1500LG" ,
"weapons.missiles.AGM_84D" ,
"weapons.missiles.YJ-83K" ,
"weapons.missiles.AIM_54C_Mk47" ,
"weapons.missiles.BRM-1_90MM" ,
"weapons.missiles.Ataka_9M120F" ,
"weapons.droptanks.1100L Tank" ,
"weapons.bombs.BAP_100" ,
"weapons.adapters.lau-88" ,
"weapons.missiles.P_40T" ,
"weapons.missiles.GB-6" ,
"weapons.bombs.FAB-250M54TU" ,
"weapons.missiles.DWS39_MJ1" ,
"weapons.missiles.CM-802AKG" ,
"weapons.bombs.FAB_250" ,
"weapons.missiles.C_802AK" ,
"weapons.bombs.SD_500_A" ,
"weapons.bombs.GBU_32_V_2B" ,
"weapons.containers.marder" ,
"weapons.missiles.ADM_141B" ,
"weapons.bombs.ROCKEYE" ,
"weapons.missiles.BK90_MJ1" ,
"weapons.containers.BTR-80" ,
"weapons.bombs.SAM ROLAND ADS [34720lb]" ,
"weapons.containers.wmd7" ,
"weapons.missiles.C-701T" ,
"weapons.missiles.AIM-7E-2" ,
"weapons.nurs.HVAR" ,
"weapons.containers.HMMWV_M1043" ,
"weapons.droptanks.PTB-800-MIG21" ,
"weapons.missiles.AGM_114" ,
"weapons.bombs.APC M1126 Stryker ICV [29542lb]" ,
"weapons.bombs.APC M113 Air [21624lb]" ,
"weapons.bombs.M_117" ,
"weapons.missiles.AGM_65D" ,
"weapons.droptanks.MB339_TT320_L" ,
"weapons.missiles.AGM_86" ,
"weapons.bombs.BDU_45LGB" ,
"weapons.missiles.AGM_65H" ,
"weapons.nurs.RS-82" ,
"weapons.nurs.SNEB_TYPE252_F1B" ,
"weapons.bombs.BL_755" ,
"weapons.containers.F-15E_AAQ-28_LITENING" ,
"weapons.nurs.SNEB_TYPE256_F1B" ,
"weapons.missiles.AGM_84H" ,
"weapons.missiles.AIM_54" ,
"weapons.missiles.X_31A" ,
"weapons.bombs.KAB_500Kr" ,
"weapons.containers.SPS-141-100" ,
"weapons.missiles.BK90_MJ2" ,
"weapons.missiles.Super_530D" ,
"weapons.bombs.CBU_52B" ,
"weapons.droptanks.PTB-450" ,
"weapons.bombs.IFV MCV-80 [34720lb]" ,
"weapons.containers.2-c9" ,
"weapons.missiles.AIM-9JULI" ,
"weapons.droptanks.MB339_TT500_R" ,
"weapons.nurs.C_8CM" ,
"weapons.containers.BARAX" ,
"weapons.missiles.P_40R" ,
"weapons.missiles.YJ-12" ,
"weapons.missiles.CM_802AKG" ,
"weapons.nurs.SNEB_TYPE254_H1_YELLOW" ,
"weapons.bombs.Durandal" ,
"weapons.droptanks.i16_eft" ,
"weapons.droptanks.AV8BNA_AERO1D_EMPTY" ,
"weapons.containers.Hercules_Battle_Station_TGP" ,
"weapons.nurs.C_8CM_VT" ,
"weapons.missiles.PL-12" ,
"weapons.missiles.R-3R" ,
"weapons.bombs.GBU_54_V_1B" ,
"weapons.droptanks.MB339_TT320_R" ,
"weapons.bombs.RN-24" ,
"weapons.containers.2c6m" ,
"weapons.bombs.ARV BRDM-2 Air [12320lb]" ,
"weapons.bombs.ARV BRDM-2 Skid [12210lb]" ,
"weapons.nurs.SNEB_TYPE251_F1B" ,
"weapons.missiles.X_41" ,
"weapons.containers.{MIG21_SMOKE_WHITE}" ,
"weapons.bombs.MK_82AIR" ,
"weapons.missiles.R_530F_EM" ,
"weapons.bombs.SAMP400LD" ,
"weapons.bombs.FAB_50" ,
"weapons.bombs.AB_250_2_SD_10A" ,
"weapons.missiles.ADM_141A" ,
"weapons.containers.KBpod" ,
"weapons.bombs.British_GP_500LB_Bomb_Mk4" ,
"weapons.missiles.AGM_65E" ,
"weapons.containers.sa342_dipole_antenna" ,
"weapons.bombs.OFAB-100 Jupiter" ,
"weapons.nurs.SNEB_TYPE257_F1B" ,
"weapons.missiles.Rb 04E (for A.I.)" ,
"weapons.bombs.AN-M66A2" ,
"weapons.missiles.P_27T" ,
"weapons.droptanks.LNS_VIG_XTANK" ,
"weapons.missiles.R-55" ,
"weapons.torpedoes.YU-6" ,
"weapons.bombs.British_MC_250LB_Bomb_Mk2" ,
"weapons.droptanks.PTB_120_F86F35" ,
"weapons.missiles.PL-8B" ,
"weapons.droptanks.F-15E_Drop_Tank_Empty" ,
"weapons.nurs.British_HE_60LBFNo1_3INCHNo1" ,
"weapons.missiles.P_77" ,
"weapons.torpedoes.LTF_5B" ,
"weapons.missiles.R-3S" ,
"weapons.nurs.SNEB_TYPE253_H1" ,
"weapons.missiles.PL-8A" ,
"weapons.bombs.APC BTR-82A Skid [24888lb]" ,
"weapons.containers.Sborka" ,
"weapons.missiles.AGM_65L" ,
"weapons.missiles.X_28" ,
"weapons.missiles.TGM_65G" ,
"weapons.nurs.SNEB_TYPE257_H1" ,
"weapons.missiles.RB75B" ,
"weapons.missiles.X_25ML" ,
"weapons.droptanks.FPU_8A" ,
"weapons.bombs.BLG66" ,
"weapons.nurs.C_8CM_RD" ,
"weapons.containers.{EclairM_06}" ,
"weapons.bombs.RBK_500AO" ,
"weapons.missiles.AIM-9P" ,
"weapons.bombs.British_GP_500LB_Bomb_Mk4_Short" ,
"weapons.containers.MB339_Vinten" ,
"weapons.missiles.Rb 15F" ,
"weapons.nurs.ARAKM70BHE" ,
"weapons.bombs.AAA Vulcan M163 Air [21666lb]" ,
"weapons.missiles.X_29L" ,
"weapons.containers.{F14-LANTIRN-TP}" ,
"weapons.bombs.FAB-250-M62" ,
"weapons.missiles.AIM_120C" ,
"weapons.bombs.EWR SBORKA Air [21624lb]" ,
"weapons.bombs.SAMP250LD" ,
"weapons.droptanks.Spitfire_slipper_tank" ,
"weapons.missiles.LS-6-500" ,
"weapons.bombs.GBU_31_V_4B" ,
"weapons.droptanks.PTB400_MIG15" ,
"weapons.containers.m-113" ,
"weapons.bombs.SPG M1128 Stryker MGS [33036lb]" ,
"weapons.missiles.AIM-9L" ,
"weapons.missiles.AIM_9X" ,
"weapons.nurs.C_8" ,
"weapons.bombs.SAM CHAPARRAL Skid [21516lb]" ,
"weapons.missiles.P_27TE" ,
"weapons.bombs.ODAB-500PM" ,
"weapons.bombs.MK77mod1-WPN" ,
"weapons.droptanks.PTB400_MIG19" ,
"weapons.torpedoes.Mark_46" ,
"weapons.containers.rightSeat" ,
"weapons.containers.{US_M10_SMOKE_TANK_ORANGE}" ,
"weapons.bombs.SAB_100MN" ,
"weapons.nurs.FFAR Mk5 HEAT" ,
"weapons.bombs.IFV TPZ FUCH [33440lb]" ,
"weapons.bombs.IFV M2A2 Bradley [34720lb]" ,
"weapons.bombs.MK77mod0-WPN" ,
"weapons.containers.ASO-2" ,
"weapons.bombs.Mk_84AIR_GP" ,
"weapons.nurs.S-24A" ,
"weapons.bombs.RBK_250_275_AO_1SCH" ,
"weapons.bombs.Transport Tigr Skid [15730lb]" ,
"weapons.missiles.AIM-7F" ,
"weapons.bombs.CBU_99" ,
"weapons.bombs.LUU_2B" ,
"weapons.bombs.FAB-500TA" ,
"weapons.missiles.AGR_20_M282" ,
"weapons.droptanks.MB339_FT330" ,
"weapons.bombs.SAMP125LD" ,
"weapons.missiles.X_25MP" ,
"weapons.nurs.SNEB_TYPE252_H1" ,
"weapons.missiles.AGM_65F" ,
"weapons.missiles.AIM-9P5" ,
"weapons.bombs.Transport Tigr Air [15900lb]" ,
"weapons.nurs.SNEB_TYPE254_H1_RED" ,
"weapons.nurs.FFAR Mk1 HE" ,
"weapons.nurs.SPRD-99" ,
"weapons.bombs.BIN_200" ,
"weapons.bombs.BLU_4B_GROUP" ,
"weapons.bombs.GBU_24" ,
"weapons.missiles.Rb 04E" ,
"weapons.missiles.Rb 74" ,
"weapons.containers.leftSeat" ,
"weapons.bombs.LS-6-100" ,
"weapons.bombs.Transport URAL-375 [14815lb]" ,
"weapons.containers.{US_M10_SMOKE_TANK_GREEN}" ,
"weapons.missiles.X_22" ,
"weapons.containers.FAS" ,
"weapons.nurs.S-25-O" ,
"weapons.droptanks.para" ,
"weapons.droptanks.F-15E_Drop_Tank" ,
"weapons.droptanks.M2KC_08_RPL541_EMPTY" ,
"weapons.missiles.X_31P" ,
"weapons.bombs.RBK_500U" ,
"weapons.missiles.AIM_54A_Mk47" ,
"weapons.droptanks.oiltank" ,
"weapons.missiles.AGM_154B" ,
"weapons.containers.MB339_SMOKE-POD" ,
"weapons.containers.{ECM_POD_L_175V}" ,
"weapons.droptanks.PTB_580G_F1" ,
"weapons.containers.{EclairM_15}" ,
"weapons.containers.F-15E_AAQ-13_LANTIRN" ,
"weapons.droptanks.800L Tank Empty" ,
"weapons.containers.16c_hts_pod" ,
"weapons.bombs.AN-M81" ,
"weapons.droptanks.Mosquito_Drop_Tank_100gal" ,
"weapons.droptanks.Mosquito_Drop_Tank_50gal" ,
"weapons.droptanks.DFT_150_GAL_A4E" ,
"weapons.missiles.AIM_9" ,
"weapons.bombs.IFV BTR-D Air [18040lb]" ,
"weapons.containers.{EclairM_42}" ,
"weapons.bombs.KAB_1500T" ,
"weapons.droptanks.PTB-490-MIG21" ,
"weapons.droptanks.PTB_200_F86F35" ,
"weapons.droptanks.PTB760_MIG19" ,
"weapons.bombs.GBU-43/B(MOAB)" ,
"weapons.torpedoes.G7A_T1" ,
"weapons.bombs.IFV BMD-1 Air [18040lb]" ,
"weapons.bombs.SAM LINEBACKER [34720lb]" ,
"weapons.containers.ais-pod-t50_r" ,
"weapons.containers.{CE2_SMOKE_WHITE}" ,
"weapons.droptanks.fuel_tank_230" ,
"weapons.droptanks.M2KC_RPL_522" ,
"weapons.missiles.AGM_130" ,
"weapons.droptanks.800L Tank" ,
"weapons.bombs.IFV BTR-D Skid [17930lb]" ,
"weapons.containers.bmp-1" ,
"weapons.bombs.GBU_31" ,
"weapons.containers.aaq-28LEFT litening" ,
"weapons.missiles.Kh-66_Grom" ,
"weapons.containers.{MIG21_SMOKE_RED}" ,
"weapons.containers.U22" ,
"weapons.bombs.IFV BMD-1 Skid [17930lb]" ,
"weapons.droptanks.Bidon" ,
"weapons.bombs.GBU_31_V_2B" ,
"weapons.bombs.Mk_82Y" ,
"weapons.containers.pl5eii" ,
"weapons.bombs.RBK_500U_OAB_2_5RT" ,
"weapons.bombs.British_GP_500LB_Bomb_Mk5" ,
"weapons.containers.{Eclair}" ,
"weapons.nurs.S5MO_HEFRAG_FFAR" ,
"weapons.bombs.BETAB-500M" ,
"weapons.bombs.Transport M818 [16000lb]" ,
"weapons.bombs.British_MC_250LB_Bomb_Mk1" ,
"weapons.nurs.SNEB_TYPE251_H1" ,
"weapons.bombs.TYPE-200A" ,
"weapons.nurs.HYDRA_70_M151" ,
"weapons.bombs.IFV BMP-3 [32912lb]" ,
"weapons.bombs.APC MTLB Air [26400lb]" ,
"weapons.nurs.HYDRA_70_M229" ,
"weapons.bombs.BDU_45" ,
"weapons.bombs.OFAB-100-120TU" ,
"weapons.missiles.AIM-9J" ,
"weapons.nurs.ARF8M3API" ,
"weapons.bombs.BetAB_500ShP" ,
"weapons.nurs.C_8OFP2" ,
"weapons.bombs.GBU_10" ,
"weapons.bombs.APC MTLB Skid [26290lb]" ,
"weapons.nurs.SNEB_TYPE254_F1B_RED" ,
"weapons.missiles.X_65" ,
"weapons.missiles.R_550_M1" ,
"weapons.missiles.AGM_65K" ,
"weapons.nurs.SNEB_TYPE254_F1B_YELLOW" ,
"weapons.missiles.AGM_88" ,
"weapons.nurs.C_8OM" ,
"weapons.bombs.SAM ROLAND LN [34720b]" ,
"weapons.missiles.AIM_120" ,
"weapons.missiles.HOT3_MBDA" ,
"weapons.missiles.R-13M" ,
"weapons.missiles.AIM_54C_Mk60" ,
"weapons.bombs.AAA GEPARD [34720lb]" ,
"weapons.missiles.R-13M1" ,
"weapons.bombs.APC Cobra Air [10912lb]" ,
"weapons.bombs.RBK_250" ,
"weapons.bombs.SC_500_J" ,
"weapons.missiles.AGM_114K" ,
"weapons.missiles.ALARM" ,
"weapons.bombs.Mk_83" ,
"weapons.missiles.AGM_65B" ,
"weapons.bombs.MK_82SNAKEYE" ,
"weapons.nurs.HYDRA_70_MK1" ,
"weapons.bombs.BLG66_BELOUGA" ,
"weapons.containers.{EclairM_51}" ,
"weapons.missiles.AIM_54A_Mk60" ,
"weapons.droptanks.DFT_300_GAL_A4E" ,
"weapons.bombs.ATGM M1134 Stryker [30337lb]" ,
"weapons.bombs.BAT-120" ,
"weapons.missiles.DWS39_MJ1_MJ2" ,
"weapons.containers.SPRD" ,
"weapons.bombs.BR_500" ,
"weapons.bombs.British_GP_500LB_Bomb_Mk1" ,
"weapons.bombs.BDU_50HD" ,
"weapons.missiles.RS2US" ,
"weapons.bombs.IFV BMP-2 [25168lb]" ,
"weapons.bombs.SAMP400HD" ,
"weapons.containers.Hercules_Battle_Station" ,
"weapons.bombs.AN_M64" ,
"weapons.containers.rearCargoSeats" ,
"weapons.bombs.Mk_82" ,
"weapons.missiles.AKD-10" ,
"weapons.bombs.BDU_50LGB" ,
"weapons.missiles.SD-10" ,
"weapons.containers.IRDeflector" ,
"weapons.bombs.FAB_500" ,
"weapons.bombs.KAB_500" ,
"weapons.nurs.S-5M" ,
"weapons.missiles.MICA_R" ,
"weapons.missiles.X_59M" ,
"weapons.nurs.UG_90MM" ,
"weapons.bombs.LYSBOMB" ,
"weapons.nurs.R4M" ,
"weapons.containers.dlpod_akg" ,
"weapons.missiles.LD-10" ,
"weapons.bombs.SC_50" ,
"weapons.nurs.HYDRA_70_MK5" ,
"weapons.bombs.FAB_100M" ,
"weapons.missiles.Rb 24" ,
"weapons.bombs.BDU_45B" ,
"weapons.missiles.GB-6-HE" ,
"weapons.missiles.KD-63B" ,
"weapons.missiles.P_27PE" ,
"weapons.droptanks.PTB300_MIG15" ,
"weapons.bombs.250-3" ,
"weapons.bombs.SC_500_L2" ,
"weapons.containers.HMMWV_M1045" ,
"weapons.bombs.FAB-500M54TU" ,
"weapons.containers.{US_M10_SMOKE_TANK_YELLOW}" ,
"weapons.containers.{EclairM_60}" ,
"weapons.bombs.SAB_250_200" ,
"weapons.bombs.FAB_100" ,
"weapons.bombs.KAB_500S" ,
"weapons.missiles.AGM_45A" ,
"weapons.missiles.Kh25MP_PRGS1VP" ,
"weapons.nurs.S5M1_HEFRAG_FFAR" ,
"weapons.containers.kg600" ,
"weapons.bombs.AN_M65" ,
"weapons.bombs.AN_M57" ,
"weapons.bombs.BLU_3B_GROUP" ,
"weapons.bombs.BAP-100" ,
"weapons.containers.HEMTT" ,
"weapons.bombs.British_MC_500LB_Bomb_Mk1_Short" ,
"weapons.nurs.ARAKM70BAP" ,
"weapons.missiles.AGM_119" ,
"weapons.missiles.MMagicII" ,
"weapons.bombs.AB_500_1_SD_10A" ,
"weapons.nurs.HYDRA_70_M282" ,
"weapons.droptanks.DFT_400_GAL_A4E" ,
"weapons.nurs.HYDRA_70_M257" ,
"weapons.droptanks.AV8BNA_AERO1D" ,
"weapons.containers.{US_M10_SMOKE_TANK_BLUE}" ,
"weapons.nurs.ARF8M3HEI" ,
"weapons.bombs.RN-28" ,
"weapons.bombs.Squad 30 x Soldier [7950lb]" ,
"weapons.containers.uaz-469" ,
"weapons.containers.Otokar_Cobra" ,
"weapons.bombs.APC BTR-82A Air [24998lb]" ,
"weapons.nurs.HYDRA_70_M274" ,
"weapons.missiles.P_24R" ,
"weapons.nurs.HYDRA_70_MK61" ,
"weapons.missiles.Igla_1E" ,
"weapons.missiles.C-802AK" ,
"weapons.nurs.C_24" ,
"weapons.droptanks.M2KC_08_RPL541" ,
"weapons.nurs.C_13" ,
"weapons.droptanks.droptank_110_gal" ,
"weapons.bombs.Mk_84" ,
"weapons.missiles.Sea_Eagle" ,
"weapons.droptanks.PTB_1200_F1" ,
"weapons.nurs.SNEB_TYPE256_H1" ,
"weapons.containers.MATRA-PHIMAT" ,
"weapons.containers.smoke_pod" ,
"weapons.containers.F-15E_AAQ-14_LANTIRN" ,
"weapons.containers.{EclairM_24}" ,
"weapons.bombs.GBU_16" ,
"weapons.nurs.HYDRA_70_M156" ,
"weapons.missiles.R-60" ,
"weapons.containers.zsu-23-4" ,
"weapons.missiles.RB75" ,
"weapons.missiles.Mistral" ,
"weapons.droptanks.MB339_TT500_L" ,
"weapons.bombs.SAM SA-13 STRELA [21624lb]" ,
"weapons.bombs.SAM Avenger M1097 Air [7200lb]" ,
"weapons.droptanks.1100L Tank Empty" ,
"weapons.bombs.AN-M88" ,
"weapons.missiles.S_25L" ,
"weapons.nurs.British_AP_25LBNo1_3INCHNo1" ,
"weapons.bombs.BDU_50LD",
"weapons.bombs.AGM_62",
"weapons.containers.{US_M10_SMOKE_TANK_WHITE}" ,
"weapons.missiles.MICA_T" ,
"weapons.containers.HVAR_rocket",
"weapons.containers.LANTIRN",
"weapons.missiles.AGM_78B",
"weapons.containers.uh-60l_pilot",
"weapons.missiles.AIM-92E",
"weapons.missiles.KD_63B",
"weapons.bombs.Type_200A",
"weapons.missiles.HB-AIM-7E-2",
"weapons.containers.Spear",
"weapons.missiles.LS_6",
"weapons.containers.HB_ALE_40_0_120",
"weapons.containers.Fantasm",
"weapons.nurs.FFAR_Mk61",
"weapons.bombs.HB_F4E_GBU15V1",
"weapons.containers.HB_F14_EXT_AN_APQ-167",
"weapons.nurs.LWL_RP",
"weapons.bombs.AGM_62_I",
"weapons.containers.ETHER",
"weapons.containers.TANGAZH",
"weapons.bombs.LYSBOMB 11086",
"weapons.containers.Stub_Wing",
"weapons.missiles.AIM-9E",
"weapons.missiles.C_701T",
"weapons.bombs.BAP_100",
"weapons.missiles.CM-802AKG",
"weapons.missiles.CM-400AKG",
"weapons.missiles.C_802AK",
"weapons.missiles.KD_63",
"weapons.containers.HB_ORD_Pave_Spike_Fast",
"weapons.missiles.SPIKE_ER2",
"weapons.containers.KINGAL",
"weapons.containers.LANTIRN-F14-TARGET",
"weapons.containers.SPS-141",
"weapons.bombs.BLU-3B_GROUP",
"weapons.containers.HB_ALE_40_30_0",
"weapons.droptanks.HB_HIGH_PERFORMANCE_CENTERLINE_600_GAL",
"weapons.containers.ALQ-184",
"weapons.missiles.AGM_45B",
"weapons.bombs.BLU-3_GROUP",
"weapons.missiles.SPIKE_ER",
"weapons.nurs.ARAKM70BAPPX",
"weapons.bombs.LYSBOMB 11088",
"weapons.bombs.LYSBOMB 11087",
"weapons.missiles.KD_20",
"weapons.droptanks.HB_F-4E_EXT_WingTank",
"weapons.missiles.Rb_04",
"weapons.containers.AAQ-33",
"weapons.droptanks.HB_F-4E_EXT_Center_Fuel_Tank_EMPTY",
"weapons.droptanks.HB_F-4E_EXT_WingTank_R_EMPTY",
"weapons.droptanks.HB_F-4E_EXT_WingTank_EMPTY",
"weapons.containers.uh-60l_copilot",
"weapons.droptanks.JAYHAWK_80gal_Fuel_Tankv2",
"weapons.containers.supply_m134",
"weapons.containers.Seahawk_Pylon",
"weapons.nurs.LWL_MPP",
"weapons.nurs.S_5KP",
"weapons.missiles.AIM-92J",
"weapons.missiles.HB-AIM-7E",
"weapons.containers.ALQ-131",
"weapons.containers.HB_F14_EXT_TARPS",
"weapons.containers.MH60_SOAR",
"weapons.missiles.YJ-83",
"weapons.bombs.GBU_8_B",
"weapons.containers.HB_F14_EXT_ECA",
"weapons.bombs.BAP-100",
"weapons.nurs.M261_MPSM_Rocket",
"weapons.droptanks.SEAHAWK_120_Fuel_Tank",
"weapons.containers.SHPIL",
"weapons.bombs.GBU_39",
"weapons.nurs.S_5M",
"weapons.containers.HB_ALE_40_15_90",
"weapons.missiles.AIM-7E",
"weapons.missiles.AIM-9P3",
"weapons.missiles.AGM_12B",
"weapons.missiles.CM_802AKG",
"weapons.droptanks.JAYHAWK_120_Fuel_Dual_Tank",
"weapons.droptanks.HB_F-4E_EXT_Center_Fuel_Tank",
"weapons.containers.PAVETACK",
"weapons.missiles.LS_6_500",
"weapons.bombs.LYSBOMB 11089",
"weapons.bombs.BLU-4B_GROUP",
"weapons.containers.ah-64d_radar",
"weapons.containers.F-18-LDT-POD",
"weapons.containers.HB_ALE_40_30_60",
"weapons.bombs.LS_6_100",
"weapons.droptanks.HB_F-4E_EXT_WingTank_R",
"weapons.containers.SORBCIJA_R",
"weapons.missiles.CATM_65K",
"weapons.containers.HB_ORD_Pave_Spike",
"weapons.containers.RobbieTank1",
"weapons.containers.SKY_SHADOW",
"weapons.containers.SORBCIJA_L",
"weapons.containers.Pavehawk",
"weapons.bombs.BLG66_EG",
"weapons.missiles.AGM_12C_ED",
"weapons.missiles.AIM-92C",
"weapons.containers.MPS-410",
"weapons.missiles.HJ-12",
"weapons.containers.AAQ-28_LITENING",
"weapons.containers.F-18-FLIR-POD",
"weapons.bombs.BLU_3B_GROUP",
"weapons.containers.UH60L_Jayhawk",
"weapons.containers.BOZ-100",
"weapons.missiles.AGM_78A",
"weapons.missiles.LAU_61_APKWS_M282",
"weapons.bombs.BAP-100",
"weapons.missiles.CM-802AKG",
"weapons.bombs.BLU_3B_GROUP",
"weapons.bombs.BLU-4B_GROUP",
"weapons.nurs.S_5M",
"weapons.missiles.AGM_12A",
"weapons.droptanks.JAYHAWK_120_Fuel_Tank",
"weapons.bombs.GBU_15_V_1_B",
"weapons.bombs.BAP_100",
"weapons.bombs.BLU-3B_GROUP",
"weapons.missiles.CM_802AKG",
"weapons.bombs.BLU_4B_GROUP",
"weapons.nurs.S-5M",
}